services:
  db:
    image: postgres:15
    container_name: batterysync-db
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/BatterySync
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: batterysync-server
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres_data:
